-- MySQL Script generated by MySQL Workbench
-- петак, 17. јануар 2020. 18:54:14 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Planinarsko drustvo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Planinarsko drustvo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Planinarsko drustvo` ;
USE `Planinarsko drustvo` ;

-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Uloga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Uloga` (
  `idUloga` INT NOT NULL AUTO_INCREMENT,
  `tip` VARCHAR(45) CHARACTER SET 'binary' NOT NULL,
  PRIMARY KEY (`idUloga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Clanarina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Clanarina` (
  `idClanarina` INT NOT NULL AUTO_INCREMENT,
  `pocetak` DATETIME NOT NULL,
  `kraj` DATETIME NOT NULL,
  PRIMARY KEY (`idClanarina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Korisnik` (
  `idKorisnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `korisnickoIme` VARCHAR(45) NOT NULL,
  `sifra` VARCHAR(100) NOT NULL,
  `Uloga_idUloga` INT NOT NULL,
  `Clanarina_idClanarina` INT NULL,
  PRIMARY KEY (`idKorisnik`),
  INDEX `fk_Korisnik_Clanarina1_idx` (`Clanarina_idClanarina` ASC)  ,
  INDEX `fk_Korisnik_Uloga_idx` (`Uloga_idUloga` ASC)  ,
  CONSTRAINT `fk_Korisnik_Uloga`
    FOREIGN KEY (`Uloga_idUloga`)
    REFERENCES `Planinarsko drustvo`.`Uloga` (`idUloga`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Korisnik_Clanarina1`
    FOREIGN KEY (`Clanarina_idClanarina`)
    REFERENCES `Planinarsko drustvo`.`Clanarina` (`idClanarina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Planina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Planina` (
  `idPlanina` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlanina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Dom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Dom` (
  `idDom` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `kapacitet` INT NOT NULL,
  `Planina_idPlanina` INT NOT NULL,
  PRIMARY KEY (`idDom`),
  INDEX `fk_Dom_Planina1_idx` (`Planina_idPlanina` ASC)  ,
  CONSTRAINT `fk_Dom_Planina1`
    FOREIGN KEY (`Planina_idPlanina`)
    REFERENCES `Planinarsko drustvo`.`Planina` (`idPlanina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Rezervise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Rezervise` (
  `idRezervise` INT NOT NULL AUTO_INCREMENT,
  `pocetak` DATETIME NOT NULL,
  `kraj` DATETIME NOT NULL,
  `Korisnik_idKorisnik` INT NOT NULL,
  `Dom_idDom` INT NOT NULL,
  INDEX `fk_Rezervise_Korisnik1_idx` (`Korisnik_idKorisnik` ASC)  ,
  INDEX `fk_Rezervise_Dom1_idx` (`Dom_idDom` ASC)  ,
  PRIMARY KEY (`idRezervise`),
  CONSTRAINT `fk_Rezervise_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnik`)
    REFERENCES `Planinarsko drustvo`.`Korisnik` (`idKorisnik`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Rezervise_Dom1`
    FOREIGN KEY (`Dom_idDom`)
    REFERENCES `Planinarsko drustvo`.`Dom` (`idDom`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Staza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Staza` (
  `idStaza` INT NOT NULL AUTO_INCREMENT,
  `opis` VARCHAR(450) NOT NULL,
  `tezina` INT NOT NULL,
  `mapa` MEDIUMBLOB NULL,
  `Planina_idPlanina` INT NOT NULL,
  PRIMARY KEY (`idStaza`),
  INDEX `fk_Staza_Planina1_idx` (`Planina_idPlanina` ASC)  ,
  CONSTRAINT `fk_Staza_Planina1`
    FOREIGN KEY (`Planina_idPlanina`)
    REFERENCES `Planinarsko drustvo`.`Planina` (`idPlanina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Znamenitost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Znamenitost` (
  `idZnamenitost` INT NOT NULL AUTO_INCREMENT,
  `zakazujeSe` TINYINT(1) NOT NULL,
  `tip` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(250) NOT NULL,
  `Staza_idStaza` INT NOT NULL,
  PRIMARY KEY (`idZnamenitost`),
  INDEX `fk_Znamenitost_Staza1_idx` (`Staza_idStaza` ASC)  ,
  CONSTRAINT `fk_Znamenitost_Staza1`
    FOREIGN KEY (`Staza_idStaza`)
    REFERENCES `Planinarsko drustvo`.`Staza` (`idStaza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Izvestaj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Izvestaj` (
  `idIzvestaj` INT NOT NULL AUTO_INCREMENT,
  `sadrzaj` VARCHAR(45) NULL,
  `Rezervise_idRezervise` INT NOT NULL,
  PRIMARY KEY (`idIzvestaj`),
  INDEX `fk_Izvestaj_Rezervise1_idx` (`Rezervise_idRezervise` ASC)  ,
  CONSTRAINT `fk_Izvestaj_Rezervise1`
    FOREIGN KEY (`Rezervise_idRezervise`)
    REFERENCES `Planinarsko drustvo`.`Rezervise` (`idRezervise`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Slika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Slika` (
  `idSlika` INT NOT NULL AUTO_INCREMENT,
  `slika` MEDIUMBLOB NOT NULL,
  `Znamenitost_idZnamenitost` INT NULL,
  `Izvestaj_idIzvestaj` INT NULL,
  PRIMARY KEY (`idSlika`),
  INDEX `fk_Slika_Znamenitost1_idx` (`Znamenitost_idZnamenitost` ASC)  ,
  INDEX `fk_Slika_Izvestaj1_idx` (`Izvestaj_idIzvestaj` ASC)  ,
  CONSTRAINT `fk_Slika_Znamenitost1`
    FOREIGN KEY (`Znamenitost_idZnamenitost`)
    REFERENCES `Planinarsko drustvo`.`Znamenitost` (`idZnamenitost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Slika_Izvestaj1`
    FOREIGN KEY (`Izvestaj_idIzvestaj`)
    REFERENCES `Planinarsko drustvo`.`Izvestaj` (`idIzvestaj`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Termin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Termin` (
  `idTermin` INT NOT NULL AUTO_INCREMENT,
  `pocetak` VARCHAR(45) NOT NULL,
  `kraj` VARCHAR(45) NOT NULL,
  `Znamenitost_idZnamenitost` INT NOT NULL,
  PRIMARY KEY (`idTermin`),
  INDEX `fk_Termin_Znamenitost1_idx` (`Znamenitost_idZnamenitost` ASC)  ,
  CONSTRAINT `fk_Termin_Znamenitost1`
    FOREIGN KEY (`Znamenitost_idZnamenitost`)
    REFERENCES `Planinarsko drustvo`.`Znamenitost` (`idZnamenitost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Zakazuje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Zakazuje` (
  `idZakazuje` INT NOT NULL AUTO_INCREMENT,
  `Termin_idTermin` INT NOT NULL,
  `Rezervise_idRezervise` INT NOT NULL,
  INDEX `fk_Rezervise_has_Termin_Termin1_idx` (`Termin_idTermin` ASC)  ,
  INDEX `fk_Zakazuje_Rezervise1_idx` (`Rezervise_idRezervise` ASC)  ,
  PRIMARY KEY (`idZakazuje`),
  CONSTRAINT `fk_Rezervise_has_Termin_Termin1`
    FOREIGN KEY (`Termin_idTermin`)
    REFERENCES `Planinarsko drustvo`.`Termin` (`idTermin`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Zakazuje_Rezervise1`
    FOREIGN KEY (`Rezervise_idRezervise`)
    REFERENCES `Planinarsko drustvo`.`Rezervise` (`idRezervise`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Obilazi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Obilazi` (
  `idObilazi` INT NOT NULL AUTO_INCREMENT,
  `Znamenitost_idZnamenitost` INT NOT NULL,
  `Rezervise_idRezervise` INT NOT NULL,
  INDEX `fk_Rezervise_has_Znamenitost_Znamenitost1_idx` (`Znamenitost_idZnamenitost` ASC)  ,
  INDEX `fk_Obilazi_Rezervise1_idx` (`Rezervise_idRezervise` ASC)  ,
  PRIMARY KEY (`idObilazi`),
  CONSTRAINT `fk_Rezervise_has_Znamenitost_Znamenitost1`
    FOREIGN KEY (`Znamenitost_idZnamenitost`)
    REFERENCES `Planinarsko drustvo`.`Znamenitost` (`idZnamenitost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Obilazi_Rezervise1`
    FOREIGN KEY (`Rezervise_idRezervise`)
    REFERENCES `Planinarsko drustvo`.`Rezervise` (`idRezervise`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Planinarsko drustvo`.`Komentarise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planinarsko drustvo`.`Komentarise` (
  `idKomentarise` INT NOT NULL AUTO_INCREMENT,
  `Znamenitost_idZnamenitost` INT NOT NULL,
  `Rezervise_idRezervise` INT NOT NULL,
  `komentar` VARCHAR(250) NOT NULL,
  INDEX `fk_Rezervise_has_Znamenitost_Znamenitost2_idx` (`Znamenitost_idZnamenitost` ASC)  ,
  INDEX `fk_Komentarise_Rezervise1_idx` (`Rezervise_idRezervise` ASC)  ,
  PRIMARY KEY (`idKomentarise`),
  CONSTRAINT `fk_Rezervise_has_Znamenitost_Znamenitost2`
    FOREIGN KEY (`Znamenitost_idZnamenitost`)
    REFERENCES `Planinarsko drustvo`.`Znamenitost` (`idZnamenitost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Komentarise_Rezervise1`
    FOREIGN KEY (`Rezervise_idRezervise`)
    REFERENCES `Planinarsko drustvo`.`Rezervise` (`idRezervise`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
